- apollo/agent/agent.py
- apollo/agent/constants.py
- apollo/agent/env_vars.py
- apollo/agent/log_context.py
- apollo/agent/logging_utils.py
- apollo/integrations/base_proxy_client.py
- apollo/interfaces/cloudrun/cloudrun_log_context.py
- apollo/interfaces/cloudrun/main.py
- tests/test_agent_commands.py
- Provides a way to enable debug logging by setting env var `MCD_DEBUG_LOG` to `true`
- Includes a debug message when an operation completes, including the elapsed time
- Updates the names of the attributes in log messages used for trace_id and operation_name to `mcd_trace_id` and `mcd_operation_name`
- Uses `logging.Filter` feature to update the logging context including `trace_id` and `operation_name` for all requests, this ends up including this information in all logs, including those from other libraries, helping to get all logs related to a single operation when filtering by `mcd_trace_id`.
> KIL-2629: Logging improvements

- requirements.in
- requirements.txt
- `pyarrow` updated to 14.0.1 to fix CVE-2023-47248
- verified on our `dev` environment that `databricks-sql` (the package using `pyarrow`) is working fine
> Updated pyarrow to resolve CVE-2023-47248

- apollo/agent/agent.py
- apollo/agent/constants.py
- apollo/agent/evaluation_utils.py
- apollo/agent/proxy_client_factory.py
- apollo/agent/utils.py
- apollo/integrations/db/base_db_proxy_client.py
- apollo/integrations/redshift/redshift_proxy_client.py
- apollo/interfaces/agent_response.py
- requirements.in
- requirements.txt
- tests/test_redshift_client.py
- New Redshift proxy client that uses `psycopg2` library.
- Created a base class: `BaseDbProxyClient` that should work in the future as the base class for other database clients like Postgres, MSSQL, etc.
- Added code to discard cached clients if an exception was raised during the execution of an operation, noticed that Redshift clients keep raising errors after an Exception occurred.
> KIL-2578: [Agent] Redshift proxy client

- apollo/integrations/db/sql_server_proxy_client.py
- tests/test_sql_server_client.py
- Uses a custom cursor class `SqlServerProxyClientCursor` to override the query parameters and provided them as a tuple instead of a list for SQL Server's client
- Fixes the [sentry error](https://monte-carlo-data.sentry.io/issues/4643357426/?alert_rule_id=11714577&alert_type=issue&environment=dev&notification_uuid=4153e0de-851e-4d12-895c-3bed8cfdcf0f&project=3527635&referrer=slack): `'params' arg (<class 'list'>) can be only a tuple or a dictionary.`
> KIL-2744 Fix invalid execute params type for SQL Server proxy client

- apollo/agent/proxy_client_factory.py
- apollo/integrations/db/base_db_proxy_client.py
- apollo/integrations/db/oracle_proxy_client.py
- requirements.in
- requirements.txt
- tests/test_oracle_client.py
- Adds a new `OracleProxyClient` for processing agent executions with connection type `oracle`.
- Adds a `_process_description` hook to the `BaseDbProxyClient` that can be overridden to customize the serialization of the returned description data.
- Overrides `_process_description` in `OracleProxyClient` to handle the presence of the `DbType` values Oracle returns in place of the column type values.
> KIL-2744 Oracle DB proxy client

- .circleci/config.yml
- .pre-commit-config.yaml
- apollo/integrations/http/http_proxy_client.py
- requirements-dev.in
- requirements-dev.txt
We were encountering errors like this
```
File "/home/circleci/.pyenv/versions/3.8.18/lib/python3.8/subprocess.py", line 516, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/circleci/project/.venv/bin/python', '-m', 'nodeenv', '/home/circleci/.cache/pyright-python/nodeenv']' returned non-zero exit status 1.
```
when running pyright in CI. And according to https://github.com/RobertCraigie/pyright-python#how-pyright-for-python-works:
>This project works by first checking if node is in the PATH. If it is not, then we download node at runtime using [nodeenv](https://github.com/ekalinin/nodeenv), then install the pyright npm package using npm and finally, run the downloaded JS with node.
So we are updating the image being used to run the …
> Fix pyright linter failures in CI

- apollo/agent/proxy_client_factory.py
- apollo/integrations/db/teradata_proxy_client.py
- requirements.in
- requirements.txt
- tests/test_teradata_client.py
- Adds a new `TeradataProxyClient` for processing agent executions with connection type teradata.
- Overrides `_process_description` in `TeradataProxyClient` to convert the column type property to a string of the type name instead of an object of the class type.
> KIL-2744 Teradata proxy client

- Dockerfile
- apollo/integrations/http/http_proxy_client.py
- tests/test_databricks_client.py
- tests/test_http_client.py
- Minor improvements to `HTTP` client:
- Support `params` argument that is passed to `requests` to be used as query string parameters
- Return error type and error attributes so the `HTTPError` can be created client side
- Support auth type credentials attribute (optional and defaulting to `Bearer`) as `dbt` requires the `Authorization` header to be `Token <token>` instead of `Bearer <token>`
> KIL-2779 [Agent] dbt Cloud client

- .circleci/config.yml
- Dockerfile
- Adds a new `build-and-push-lambda` command that runs on the dev branch to publish the `mcd-pre-release-agent` to ECR, and and on the main branch to publish the `mcd-agent` image to ECR. Runs in parallel with the pre-existing `build-and-push` command so the overall build doesn't increase.
- Updates the `verify-version-in-docker-image` command to run with `python` as the entrypoint to override the default entrypoint of lambda-based images.
- https://github.com/monte-carlo-data/infrastructure/pull/645
> KIL-2772 Build lambda image for ECR

- Dockerfile
- requirements.in
- requirements.txt
We're getting the error described [here](https://community.snowflake.com/s/article/Python-Connector-fails-to-connect-with-LibraryNotFoundError-Error-detecting-the-version-of-libcrypto).
As a workaround, we're adding a direct dependency to `oscrypto`'s GitHub repository, this also requires installing `git` in the images so it's available when Python dependencies are installed using `pip`.
> KIL-2794 [Agent] Snowflake error detecting the version of libcrypto

- apollo/agent/constants.py
- apollo/agent/serde.py
We were getting the error: `Object of type Decimal is not JSON serializable` when returning results for `Redshift` queries ([Sentry](https://monte-carlo-data.sentry.io/issues/4633743052/events/latest/?project=3527635&referrer=latest-event)).
We started seeing this now because we're serializing the response to calculate the size, if we don't do that, `Flask` takes care of the serialization and serializes `decimal` values as strings which is wrong, as we need the value client side to be a `decimal`.
> Added support for decimal type serialization

- apollo/agent/constants.py
- apollo/agent/serde.py
- tests/test_mysql_client.py
Adds support for `bytes` data types, including support for MySQL's `bit` data type that is returned by the connector as a `bytes` object
> [Agent] added support for bytes data type

- Dockerfile
With this new AWS release to their Docker images, `yum` is being replaced with `dnf`.
@mrostan and I's testing unfortunately proved this will not be a straight forward switch
This PR pins the base docker version to before this release so that `yum` is still supported. Will investigate switching over to `dnf` in a future ticket
> pins base docker image version to older version to keep support for yum

- Dockerfile
- apollo/agent/proxy_client_factory.py
- apollo/integrations/db/azure_database_proxy_client.py
Azure Dedicated SQL Pool and Azure SQL Database connection types can use the exact same client. This PR renames the Azure client to be more generic and maps both connection types to the same client
Tested in dev using the test-lambda-dev account and adding a sql pool and SQL Database connection + sql monitor to confirm they work
> add support for Azure SQL Database

- apollo/agent/proxy_client_factory.py
- apollo/integrations/db/sap_hana_proxy_client.py
- requirements.in
- requirements.txt
- tests/test_sap_hana_client.py
Adds proxy client for SAP HANA and unit tests
Tested in `test.aws_agent` with the AWS remote agent, was able to create integration and run SQL monitor
> add sap hana proxy client

- apollo/interfaces/lambda_function/direct_updater.py
- tests/test_aws_platform.py
Update the values returned for `infra_details` when terraform is in use so the result is consistent with the result for CloudFormation and the `cli` works fine.
> Update infra_details for terraform to match cloudformation

- apollo/agent/agent.py
Before, `get_update_logs` operation was checking for upgrades enabled, but that's wrong as disabling remote upgrades shouldn't prevent us from performing read-only operations like getting CF events.
> Enable upgrade logs even if remote upgrades are disabled

- apollo/integrations/http/http_proxy_client.py
- tests/test_http_client.py
This PR updates the `HttpProxyClient` to support custom authentication headers. 
For example, [authentication for the Pinecone API](https://docs.pinecone.io/docs/authentication#add-a-header-to-an-http-request) requires an API token be passed in an `Api-Key` header.
> KIL-2910: update HTTP proxy client to support custom auth headers

- apollo/interfaces/azure/function_app.py
- Azure Durable Functions store data for all requests (input and output data) forever, and as discussed [here](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-instance-management?tabs=python#purge-instance-history) we can use the `Orchestration Client API` to manually purge the history for a given instance or all instances created in a given period.
- This PR introduces a timer-triggered function that executes every 12 hours (hard-coded at 3 AM and 3 PM) and deletes the history for all completed (failed or succeeded) instances that were executed more than 1 day ago.
> [Azure Agent] Cleanup Durable Functions history periodically

- requirements.in
https://github.com/monte-carlo-data/apollo-agent/pull/72 upgraded a few libraries, specifically `jinja2` and `pycryptodome` had to keep the previous version as the minimum to prevent breaking the data-collector build
> Fix versions in requirements.in introduced by PR 72

- apollo/agent/agent.py
- apollo/agent/constants.py
- apollo/agent/models.py
- apollo/interfaces/agent_response.py
- apollo/interfaces/azure/function_app.py
- apollo/interfaces/generic/main.py
- tests/test_agent_response.py
Two new settings are now supported for operations:
- `compress_response_file`: controls whether file saved to the bucket (when a pre-signed url is returned) is compressed or not, defaults to `False`.
- `compress_response_threshold_bytes`: when the size is larger than this threshold and a pre-signed url is not used, the response is compressed and the result is sent with `Content-Type: application/gzip`. Defaults to `0` (disabled).
> KIL-2988: Add support for compressing large results

- apollo/integrations/db/oracle_proxy_client.py
- apollo/interfaces/azure/function_app.py
- Configured Oracle connections to send keep-alive packets every minute
- Added more information to the status for async tasks to help on testing, the status endpoint now returns the `created_time` and `last_updated_time` attributes from the task, we can use to check when it started and when it completed.
> Azure: TCP Keep Alive settings for Oracle connections

- apollo/interfaces/azure/azure_platform.py
- tests/test_azure_platform.py
- We were getting the app-insights resource-id from a `hidden-link` attribute that is no longer present, switched to get it from `APPINSIGHTS_RESOURCE_ID` environment variable.
- Related to https://github.com/monte-carlo-data/terraform-azurerm-mcd-agent/pull/1
> Update Azure platform to get app-insights resource-id from env var

- apollo/integrations/azure_blob/azure_blob_base_reader_writer.py
- Fixed `upload_file` (that uploads a local file to the storage) for Azure Blob storage as it wasn't opening the file in binary mode and it was raising an `utf-8` encoding error
> Azure Agents: fix looker-git

- apollo/integrations/databricks/databricks_sql_warehouse_proxy_client.py
- tests/test_databricks_client.py
Updated `DatabricksSqlWarehouseProxyClient` client to extend `BaseDbProxyClient` and implement the right pre-serialization processing for results, as for example dates were not being serialized in the right way (and failed to be serialized when using Azure durable functions)
> Fix results serialization for Databricks

- apollo/integrations/db/base_db_proxy_client.py
- apollo/integrations/db/mysql_proxy_client.py
- apollo/integrations/db/presto_proxy_client.py
Updates the `MysqlProxyClient` to handle ssl certificate options similarly to how we handle it for `PrestoProxyClient`. This allows us to use the same mysql proxy client for both MySQL transactional databases and Hive MySQL metastores.
> KIL-3013 Add ssl support to MySQL proxy client

- apollo/agent/proxy_client_factory.py
- apollo/integrations/db/hive_proxy_client.py
- requirements.in
- requirements.txt
- tests/test_hive_client.py
- Creates a new `HiveProxyClient` that extends the `BaseDbProxyClient` for use with hive connection types.
- Uses a custom extension of `hive.Connection` (`HiveProxyConnection`) in order to use a custom extension of `hive.Cursor` (`HiveProxyCursor`) which adds an `async_execute` method to wait for incomplete queries as well as canceling queries running longer than the specified timeout.
> KIL-3014 Hive proxy client

- requirements-azure.in
- requirements-azure.txt
We were experiencing an issue with Azure Functions when a VNet was enabled.
The startup process was never ending, after some research we found that the call to `configure_azure_monitor` that initializes OpenTelemetry was hanging up and never ending, that was causing the Azure Function startup process to timeout and to keep restarting itself, making the function not available.
The issue gets fixed updating `azure-monitor-opentelemetry` to `1.2.0`.
There's a similar but reported [here](https://github.com/Azure/azure-sdk-for-python/issues/33289) but with no mention to VNet.
> Update azure-monitor-opentelemetry to fix the startup issue using a VNet

- apollo/interfaces/lambda_function/cf_updater.py
- tests/test_cf_updater.py
- Added a new parameter to the upgrade operation for AWS Agents that can be used to force the upgrade to be performed using a "direct upgrade" that updates the `ImageUri` attribute directly in the Lambda function instead of performing a CF Stack update.
- Intended to be used only in cases where the CF update is not working properly
- To use it, pass the `UseDirectUpdate` parameter in the CLI:
```shell
montecarlo agents upgrade --agent-id <AGENT_ID> --params '{"UseDirectUpdate": true}'
```
- Improved the code in `CFUpdater` by declaring args in the `update` method instead of getting them from `kwargs`
> KIL-3085: Support direct upgrades when CF Template is used

- apollo/agent/serde.py
- tests/test_snowflake_client.py
Snowflake queries returning binary data are returning instances of `bytearray` instead of `bytes`, this PR fixes the serialization to support it and serialize it using Base 64 encoding as we do for `bytes`.
> Add support for bytearray result type

- apollo/agent/evaluation_utils.py
- apollo/agent/proxy_client_factory.py
- apollo/agent/serde.py
- tests/test_oracle_client.py
- tests/test_snowflake_client.py
- Added support for bytes in credentials, for example for Snowflake private key, bytes are sent using the same encoding used for non-serializable data types in the operation itself.
> Add support for bytes data type in credentials

- apollo/integrations/db/azure_database_proxy_client.py
- apollo/integrations/db/sql_server_proxy_client.py
- tests/test_azure_dedicated_sql_pool_client.py
- tests/test_sql_server_client.py
- Same fix as this [DC pr](https://github.com/monte-carlo-data/data-collector/pull/1083)
- The `pyodbc` client used by Azure Dedicated SQL pool, Azure SQL DB and SQL Server does not support the data type `datetimeoffset`. 
- If a SQL Monitor tries to return a datetimeoffset column in the results or uses a `select *` that includes a datetimeoffset, the monitor run fails with: 
> ('ODBC SQL type -155 is not yet supported. column-index=0 type=-155', 'HY106') (ProgrammingError)
- GitHub [issue](https://github.com/mkleehammer/pyodbc/issues/134#issuecomment-452893948)
- Purposed [solution](https://github.com/mkleehammer/pyodbc/wiki/Using-an-Output-Converter-function) I am implementing
- In dev account `AWS Agent Test`, using aws remote agent, created a Azure SQL DB connection
- Create a sql …
> Fix: pyodbc client support for datetimeoffset data type

- apollo/agent/proxy_client_factory.py
- apollo/integrations/aws/msk_proxy_client.py
- tests/test_msk_client.py
This PR adds `boto3` proxy clients for MSK [Kafka](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/kafka.html) and [Kafka Connect](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/kafkaconnect.html).
> KIL-3109: add boto3 proxy clients for AWS MSK

- .circleci/config.yml
- .circleci/trufflehog_config/allowlist.json
We have the same coverage with github advanced security.
> [CI] Trufflehog scan is no longer needed in CI

- apollo/integrations/redshift/redshift_proxy_client.py
This feature was added as a workaround for the query to retrieve Redshift query logs failing due to UTF decoding errors.
It basically disables the string decoding in the driver and allow us to decode it later.
> Support disabling Redshift driver decoding

- apollo/integrations/db/base_db_proxy_client.py
- Closes the DB Proxy client's connection on deletion of the object
- FIX: Properly ends Session in Teradata so sessions are not left in `IDLE` state
> Close DB Proxy Client's connection on deletion

- apollo/integrations/s3/s3_base_reader_writer.py
- apollo/integrations/s3/s3_reader_writer.py
For regions created after 3-20-2019 (like `af-south-1`) you need to use the regional endpoint when generating pre-signed URLs, if not the url is invalid and it fails with a `400` error like:
```
The af-south-1 location constraint is incompatible for the region specific endpoint this request was sent to.
```
One of the available fixes (for more information: https://github.com/boto/boto3/issues/3015) is to create a second client with the regional URL and use it to generate the pre-signed URL.
> Fixed pre-signed urls for regions like af-south-1

- apollo/interfaces/azure/function_app.py
- requirements-azure.in
- requirements-azure.txt
- Updated all azure specific packages to latest available version, which includes upgrading `aiohttp` to `3.9.3` and fixing https://github.com/monte-carlo-data/apollo-agent/security/dependabot/17
- `function_app` decorator is no longer supported for durable functions, so decoration to set the name for the cleanup function was removed
> Update aiohttp version to fix CVE-2024-23334

- apollo/agent/scripts.py
- tests/sample_scripts/script_builtins_valid.py
RestrictedPython requires an `_apply_` builtin to be available to use constructions like `func(**({"a": 1}))`.
Allow these constructions when running agent scripts.
> add support for RestrictedPython _apply_

- apollo/agent/agent.py
- apollo/agent/models.py
- apollo/interfaces/lambda_function/aws_utils.py
- apollo/interfaces/lambda_function/cf_updater.py
- apollo/interfaces/lambda_function/cf_utils.py
- apollo/interfaces/lambda_function/direct_updater.py
- tests/test_cf_updater.py
- As part of the health endpoint we're getting the current image (we get it from CloudFormation or directly from the Lambda if Terraform is being used)
- This operation can take a long time to execute if connections to CloudFormation or Lambda endpoints are not allowed, as the default timeout and retry policies will take between 4 or 5 minutes to fail.
- This PR reduces the timeout used when getting the current image to `10` seconds and a single retry, meaning it would take around 20 seconds to fail. It also updates the health endpoint to succeed even if we weren't able to get the current image, it just includes a new warning message with the error received and a `null` value in the image.
- *Note*: for `lambda` clients the `connect_timeout` setting is not working as expected, and setting …
> AWS agent: timeout earlier when getting current image in health endpoint

- apollo/integrations/s3/s3_base_reader_writer.py
- apollo/integrations/s3/s3_reader_writer.py
- apollo/integrations/storage/base_storage_client.py
- When the agent is configured in a VPC with no external access and without the required S3 VPC endpoint, the call to `is_bucket_private` might take minutes to timeout
- This PR introduces a new method `check_storage_access` that can be called from the DC to validate connectivity to the S3 endpoints and also calls it as part of `is_bucket_private` to automatically include it as part of the validation triggered from the DC
> AWS Agent: timeout earlier when checking storage if no S3 access

- apollo/interfaces/azure/function_app.py
Added two endpoints:
- `/async/api/v1/queue/info` to return the number of `pending` and `completed` task instances in the specified time window
```json
{
"created_time_from": "2024-04-16T00:00:00Z",
"created_time_to": "2024-04-16T12:00:00Z"
}
```
would return:
```json
{
"pending_instances": 0,
"completed_instances": 1230
}
```
- `/async/api/v1/cleanup` to purge all task instances in a given time period, optionally can delete `pending` tasks
```json
{
"created_time_from": "2024-04-16T00:00:00Z",
"created_time_to": "2024-04-16T12:00:00Z",
"include_pending": false
}
```
would return:
```json
{
"deleted_instances": 1230,
}
```
> KIL-3578 endpoints to help troubleshooting issues with Azure Durable Functions

- apollo/interfaces/azure/durable_functions_utils.py
- apollo/interfaces/azure/function_app.py
- tests/test_azure_platform.py
- Added code to terminate pending instances when cleanup with `include_pending=true` is called, this is because calling `purge` is not enough to cancel `pending` tasks.
- Switched from the raw dictionary to a data class object for the requests to this class
> KIL-3578: terminate pending tasks when cleanup(include_pending=True) is called

- .circleci/config.yml
Build updated to:
- Move the building of the AWS image to a new step that first builds the image and then uploads it to Docker Hub first and then to ECR (before we were building it first to upload it to Docker and then building it again to upload it to ECR)
- The AWS image is uploaded now to the new ECR repo in the corresponding CaaS account
- Then it is uploaded to the previous ECR repo in dev/prod account, for compatibility reasons, this step will be removed eventually
- Ubuntu images (from circleci) updated to `current` as the previous image we were using is now deprecated
> Upload AWS image to CaaS agent repo

- apollo/agent/agent.py
- apollo/agent/proxy_client_factory.py
- apollo/integrations/base_proxy_client.py
- apollo/integrations/databricks/databricks_sql_warehouse_proxy_client.py
- apollo/integrations/db/azure_database_proxy_client.py
- apollo/integrations/db/base_db_proxy_client.py
- apollo/integrations/db/hive_proxy_client.py
- apollo/integrations/db/motherduck_proxy_client.py
- apollo/integrations/db/mysql_proxy_client.py
- apollo/integrations/db/oracle_proxy_client.py
- apollo/integrations/db/postgres_proxy_client.py
- apollo/integrations/db/presto_proxy_client.py
- apollo/integrations/db/sap_hana_proxy_client.py
- apollo/integrations/db/sql_server_proxy_client.py
- apollo/integrations/db/teradata_proxy_client.py
- apollo/integrations/snowflake/snowflake_proxy_client.py
- tests/test_redshift_client.py
- Added code to clear the context, a cyclic reference was causing the context to be retained until the GC runs, causing the client to be retained too and released later than expected.
- Added code to explicitly close the client (if cache is not used) after the operation completes
- Added log messages when Redshift connections are opened/closed
> Improve client management to release memory earlier, added connection logs for Redshift

- requirements-azure.in
- requirements-azure.txt
- updates aiohttp to 3.9.4
- I checked and the parent dependency, `azure-functions-durable`, does not have a patch yet resolving this vuln. so we need to update aiohttp directly
- ✔️ merged to dev
> chore: update aiohttp

- apollo/agent/env_vars.py
- apollo/interfaces/azure/azure_updater.py
- apollo/interfaces/azure/function_app.py
- apollo/interfaces/azure/log_context.py
- apollo/interfaces/generic/main.py
- tests/test_azure_platform.py
Multiple improvements to Azure Agents:
- Add more logging to link MC trace ids with Azure Durable Functions operations so we can identify queries causing issues in durable functions
- Fix in `AzureLogContext` to use thread locals to store the context, this could be causing the wrong context to be logged when multiple operations were running at the same time.
- Ability to restart an agent: internally it uses the "update" support and sets a new environment var that is used to force the restart and also to track last time the agent was updated or restarted: `MCD_LAST_UPDATE_TS`
- "Abandon": Durable Functions activities are abandoned after `885` seconds by default, this is intentionally before the Azure Function timeout (configured with `900` seconds) to prevent the task to be automatically …
> Azure Agent improvements: logging, restart and time outs

- apollo/interfaces/azure/durable_functions_utils.py
- apollo/interfaces/azure/function_app.py
- tests/test_azure_platform.py
We detected that tasks that failed due to high memory or cpu usage (or crashes with exit codes 137 or 139) are retried multiple times and could be potentially executed forever if they crash (or get killed) again every time they are executed.
This PR adds code to prevent starting a task after the timeout period, this is because the client won't be waiting for the result and it doesn't make sense to keep trying, it also helps preventing to execute the task forever.
> Azure Agent: don't start tasks after the timeout period

- apollo/agent/agent.py
- apollo/interfaces/generic/main.py
- apollo/validators/validate_network.py
- tests/test_health_network.py
- `/api/v1/test/network/dns?host=HOSTNAME` can now be used to perform a DNS lookup operation and get the IP addresses mapped to the specified hostname
> Add new endpoint to test DNS lookups

- Dockerfile
- requirements-azure.txt
- requirements-cloudrun.in
- requirements-cloudrun.txt
- requirements-dev.txt
- requirements.in
- requirements.txt
- `urllib3==2.0.7` is vulnerable to `CVE-2024-37891`
- This PR updates it to `2.2.2` and additionally:
- Updates `tableauserverclient` to `master` branch as `0.31` depends on `urllib3==2.0.7` and `0.32` wasn't released yet
- Updates `boto3` to `1.34.135` to avoid version conflicts
- The `Dockerfile` for the Lambda agent is updated to upgrade the `urllib3` version included in the base image from `1.26.18` to `1.26.19` to fix the same vulnerability.
> VULN: Upgrade `urllib3` from `2.0.7` to `2.2.2`

- requirements.in
There was a missing whitespace after the Tableau repo URL that causes an error when the agent is imported from dc
> Fix dependency syntax in requirements.in 

- Dockerfile
- requirements-azure.txt
- requirements-cloudrun.in
- requirements-cloudrun.txt
- requirements-dev.txt
- requirements.in
- requirements.txt
- Applied library upgrades from https://github.com/monte-carlo-data/apollo-agent/pull/126 adding a restriction to `numpy` to be `<2.0.0` and prevent the `numpy.dtype` error described [here](https://github.com/numpy/numpy/issues/26710) that affected `Databricks` connectivity.
> Re-applied vulnerability fixes from 0.5.15 restricting `numpy<2.0.0`

- .circleci/config.yml
- Added steps to update and validate test agents as part of the build. Golden accounts in dev and prod are used.
- The build for the merge queue updates the production agents with the pre-release code and runs the validations before merging to `main`.
- Build improved to define `generate-version-number-prod`/`generate-version-number-dev` commands and remove some duplicated lines
> Test integrations as part of the build

- requirements.in
- requirements.txt
We're seeing some very strange issues with our Glue Integration (https://linear.app/montecarlodata/issue/MES-494/glue-getdatabases-returning-empty-responses-despite-having-access, https://linear.app/montecarlodata/issue/MES-306/investigate-schema-changing-for-old-mutual, https://linear.app/montecarlodata/issue/MES-460/old-mutual-glue-metadata-collection-timing-out) and want to bump the boto version. There is some difference in the Glue client between the version we're on now and the most updated version.
> MES-306 - update boto

- apollo/agent/proxy_client_factory.py
- apollo/integrations/db/dremio_proxy_client.py
- tests/test_dremio_client.py
- Add support for Dremio integration
- use Pyarrow FlightClient to execute and fetch results
- Create a description object from the Pyarrow FlightStreamReader schema to return to the collector
> Add support for Dremio integration

- requirements-azure.txt
- requirements-cloudrun.txt
- requirements.in
- requirements.txt
Upgraded cryptography to v43.0.1 and all the necessary dependencies
In `dev.apollo.agent@montecarlodata.com` account I updated all the agents to use the latest version (v1328):
Scheduler runs:
No errors in the last 4 hours ([link](https://app.datadoghq.com/logs?query=service%3A%28node1403%2A%20OR%20node2421%2A%20OR%20node1561%2A%20OR%20node1562%2A%20OR%20node1754%2A%20OR%20node1189%2A%29%20env%3Adev%20status%3Aerror&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&saved-view-id=1668586&storage=hot&stream_sort=desc&viz=stream&from_ts=1727181211680&to_ts=1727195611680&live=true)):
> VULN-415: Upgraded dependencies to upgrade cryptography to v43.0.1

- apollo/agent/agent.py
- apollo/interfaces/generic/main.py
- apollo/validators/validate_network.py
- tests/test_health_network.py
- Added a new networking test to validate `HTTP` connections, similar to the `TCP` related operations
- It takes the URL to test, a flag `include_response` indicating if the response should be sent back and the `timeout` in seconds
> Add HTTP connection validator

- requirements.in
- requirements.txt
Updates the databricks-sql-connector library to the most recent version (3.5.0) for the sake of a vulnerability in the logging of potentially sensitive information
> VULN-413 - update databricks sql connector to version 3.5.0

- Dockerfile
```
➜ docker build --platform=linux/amd64 -t lambda --target lambda .
➜ docker run --rm -it --entrypoint /bin/bash lambda
bash-5.2# openssl version
OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)
bash-5.2# dnf -y install binutils
bash-5.2# strings /lib64/libssl.so.3.0.8 | grep version | grep openssl
{"type":"rpm","name":"openssl","version":"3.0.8-1.amzn2023.0.14","architecture":"x86_64","osCpe":"cpe:2.3:o:amazon:amazon_linux:2023"}
```
- **Version:** `3.0.8-1.amzn2023.0.14`
```
➜ docker build --platform=linux/amd64 -t lambda --target lambda .
➜ docker run --rm -it --entrypoint /bin/bash lambda
bash-5.2# openssl version
OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)
bash-5.2# dnf -y install binutils
bash-5.2# strings /lib64/libssl.so.3.0.8 | grep version | grep …
```
> Update openssl from 3.0.8-1.amzn2023.0.14 to 3.0.8-1.amzn2023.0.16

- Dockerfile
- requirements-azure.in
- requirements-azure.txt
This PR:
- updates `sqlite3` to `3.40.1-2+deb12u1` to fix a vulnerability (VULN-469)
- updates `viztracer` to `0.17.1` to fix a vulnerability (VULN-471)
- updates `openssl` to `3.0.15-1~deb12u1` to fix a critical vulnerability reported by Docker Scout and detected during the fix for the other two issues 
Tested in dev and confirmed the issues are no longer reported by Aikido
> Azure Agent vulnerabilities: sqlite3, viztracer and openssl updated

- requirements-dev.txt
- requirements.in
- requirements.txt
Update the werkzeug library to version 3.1.0.
Context:
https://linear.app/montecarlodata/issue/VULN-458/small-upgrade-for-werkzeug
https://app.aikido.dev/issues/3251889/detail
Pushed to dev and updated MC agents:
https://us-east-1.console.aws.amazon.com/ecr/repositories/private/404798114945/mcd-pre-release-agent/_/image/sha256:ec751047d4c60fb61a3b3cde90c28550f0217eb4e3d1578023ef7766253796c1/details?region=us-east-1
Image tags **latest, 1.2.4rc1434**
> ilamden/VULN-458 bump werkzeug to 3.1.0 [apollo-agent]

- apollo/integrations/databricks/databricks_sql_warehouse_proxy_client.py
- apollo/integrations/http/http_proxy_client.py
- requirements.in
- requirements.txt
This PR adds the ability to support databricks m2m oauth. As part of this, we need to now include the databricks sdk package.
> MES-1053 - add support for databricks m2m oauth

- requirements.in
- requirements.txt
The old version of the DBX sdk did not support non-AWS Databricks environments using OAuth. We didn't catch it because we only have AWS Databricks environments for MC to test against (and use in prod).
> MES-1053 - update databricks sdk

- apollo/interfaces/azure/host.json
Upgrade extension bundle to upgrade vulnerable messagepack dependency.
See: https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-register#extension-bundles
> [VULN-453] upgrade azure extension bundle to 4.x

- apollo/agent/constants.py
- apollo/agent/serde.py
- tests/test_snowflake_client.py
Time fields were not supported and returning them was actually causing this error:
```
Object of type time is not JSON serializable
```
> Fix JSON serialization error returning `time` fields

- requirements.in
- requirements.txt
https://linear.app/montecarlodata/issue/VULN-456/small-upgrade-for-snowflake-connector-python
> VULN-456 - snowflake-connector-python bump to 3.12.4

- apollo/integrations/tableau/tableau_proxy_client.py
Add Tableau JWT scopes `tableau:labels:read`, `tableau:labels:update`, `tableau:labels:create` which are used for managing Labels on assets. This will let us read and create Data Quality Warnings on Tableau assets when connected through a connected_app
> Support Tableau Data Quality Warnings through Connected Apps

- requirements.in
- requirements.txt
- Upgraded teradatasql and pycryptodome dependencies
- Upgraded RestrictedPython from v7.4 to 8.0 to fix a high vuln issue
Test:
Upgraded agents in dev:
Tested Azure Agent:
Tested GCP Agent:
Tested AWS Agent:
Tested Teradata Integration:
Triggered Metadata collection for Teradata (no errors):
> VULN-463: Upgraded teradatasql and pycryptodome dependencies

- apollo/integrations/s3/s3_base_reader_writer.py
- apollo/integrations/s3/s3_reader_writer.py
- tests/test_s3_storage_client.py
- Removed SSE parameter when writing S3 objects (the same as https://github.com/monte-carlo-data/data-collector/pull/1589 for the DC)
- Configured the S3 client used to generate pre-signed URLs with Signature V4 enabled
- Updated unit tests
> TEA-38: Use Signature V4 for S3 pre-signed URLs

- Dockerfile
- resources/lambda/openssl/openssl_tls1.cnf
- resources/lambda/openssl/opensslcnf_tls1.config
Creates a `resources/lambda/openssl` directory for optional openSSL config files
> Add Optional openSSL Config to Agent Resources

- .pre-commit-config.yaml
- apollo/agent/constants.py
- apollo/agent/proxy_client_factory.py
- apollo/agent/serde.py
- apollo/integrations/aws/s3_proxy_client.py
- tests/test_s3_client.py
At the moment we need to download `athena` results by making calls to get_query_results. The maximum page size to return is 1000, which is too low when fetching million of results (eg. for metric monitors with very high segment count), requiring too many roundtrips and long execution times to execute a monitor run or backfill job.
Add an S3 proxy client to support downloading athena result files from S3 and reduce the number of roundtrips. 
I'm adding a separate proxy client instead of using the `StorageClient`, as storage client API is geared to represent the MC storage agent specifically.
> add support for an s3 proxy client

- .circleci/config.yml
Right now as part of the build we run in the merge queue we upload an image to the ECR dev repo in order to update the "golden" AWS agents, but we upload it only to the "new" ECR Repo in the CaaS account.
This causes the latest image to be only in the "new" ECR repo and updating an agent using the "old" ECR repo to fail.
This PR will make the image available also in the old repo.
> Upload the lambda image to the "legacy" ECR Dev repo for merge-queue builds

- apollo/integrations/db/base_db_proxy_client.py
- apollo/integrations/db/teradata_proxy_client.py
- tests/test_teradata_client.py
- Add support for Teradata SSL connections
- Add method to SslOptions that writes ca-data to a temp file to be passed to the Teradata client
- Adds unit test
> add Teradata SSL support using SslOptions, add unit tests

- setup.cfg
`setuptools` most recent versions deprecated the `-` and only accept `_` in key names.
> Change setup.cfg to adhere to new setuptools format

- apollo/integrations/tableau/tableau_proxy_client.py
- tests/test_tableau_client.py
- Allow setting Tableau `verify_ssl` connection parameter when making direct API calls
> Set Tableau verify_ssl parameter when making direct API calls

- apollo/credentials/asm.py
- apollo/credentials/base.py
- apollo/credentials/env_var.py
- tests/credentials/test_asm.py
- tests/credentials/test_env_var.py
in the DC we specify some hard coded values that we want to include in `connect_args`. instead of requiring customers to include these hard coded values in their self-hosted creds, lets merge the `connect_args` objects from the DC and provided by the customer
context: https://montecarlodata.slack.com/archives/C083XJFGN2X/p1744323378271009
> feat: merge connect_args from dc and external creds

- requirements.in
- requirements.txt
Upgrade `teradata` to upgrade golang.org/x/crypto crypto version to 0.36.0
See: https://github.com/Teradata/python-driver?tab=readme-ov-file#change-log
> Upgrade teradatasql (VULN-555)

- Dockerfile
**How I tested this change:**
From my local machine:
```sh
cd apollo-agent
docker build -t lambda_agent --target lambda --platform=linux/amd64 .
docker run --entrypoint /bin/sh --rm --platform linux/amd64 -it lambda_agent
```
Then from inside the container:
```sh
sh-5.2# ls -R / | grep -Ei "ssl.*so"
libssl.so.3
libssl.so.3.2.2
SSLeay.so
_ssl.cpython-312-x86_64-linux-gnu.so
mybusinesslodging.v1.json
libssl-3e69114b.so.1.1
ssl_wrap_socket.py
ssl_wrap_socket.cpython-312.pyc
TSSLSocket.py
TSSLSocket.cpython-312.opt-1.pyc
TSSLSocket.cpython-312.pyc
sh-5.2# python -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 3.2.2 4 Jun 2024
```
So it looks like `public.ecr.aws/lambda/python:3.12.2025.04.28.11` now includes OpenSSL version 3.2.2 🎉
> Update runtime to pick up latest openssl lib

- Dockerfile
Minor dependency updates to address vulnerabilities.
cloudrun agent:
- update kerberos (CVE-2024-26462) and passwd (CVE-2023-4641 and CVE-2023-29383)
azure agent:
- update openssl (CVE-2024-13176)
> vuln updates

- .circleci/config.yml
- Dockerfile
- The `aws-cli` orb released a new version, 5.4.0, which uses the CircleCI docker image tag `current`
- CircleCI made an update to the `current` tag to use Ubuntu 24 instead of 22. This broke our CI build when trying to use `pip install`
> Set Image Tag for CircleCI Build

- .gitignore
- README.md
- apollo/agent/proxy_client_factory.py
- apollo/integrations/db/salesforce_crm_proxy_client.py
- apollo/interfaces/generic/main.py
- requirements.in
- requirements.txt
- tests/test_salesforce_crm_client.py
This PR is part of the initial support for the Salesforce CRM client implementation. It adds the agent client that will be called by the SalesforceProxyClient from the data-collector.
To begin implementing the Salesforce CRM integration, I'd like to merge and deploy the following 5 branches to production, in this order:
1. [toffermann/mes-1510-data-pipeline-support-salesforce-crm-connection-type](https://github.com/monte-carlo-data/saas-serverless/tree/toffermann/mes-1510-data-pipeline-support-salesforce-crm-connection-type)
1. [toffermann/mes-1507-agent-add-salesforce-crm-client](https://github.com/monte-carlo-data/apollo-agent/tree/toffermann/mes-1507-agent-add-salesforce-crm-client)
1. [toffermann/mes-1506-collector-salesforce-crm-client-using-plugin-framework](https://github.com/monte- …
> MES-1507: Add salesforce-crm client

- apollo/integrations/db/teradata_proxy_client.py
- tests/test_teradata_client.py
If Teradata SSL connection is used, CA data is written to a temp file to be provided to the Teradata client. Add a unique identifier to the temp file name in case there are multiple Teradata requests from different connections going through the agent.
> Support for multiple Teradata SSL connections

- apollo/agent/proxy_client_factory.py
- apollo/integrations/db/clickhouse_proxy_client.py
- requirements.in
- requirements.txt
- tests/test_clickhouse.py
The `clickhouse-connect` package ([official python client library from Clickhouse](https://clickhouse.com/docs/integrations/python)) provides an implementation of the DB-API. Plus, gathering metadata in Clickhouse is done by running SQL queries against system tables.
Both of those things mean that our clickhouse agent can be a standard plugin/transactional-db proxy client. Other than creating the connection, `ClickhouseProxyClient` should be able to use the `BaseDbProxyClient` entirely as-is.
> MES-1703: Add clickhouse client

- apollo/agent/proxy_client_factory.py
- apollo/integrations/db/salesforce_data_cloud_proxy_client.py
- requirements-dev.in
- requirements-dev.txt
- tests/test_salesforce_data_cloud_client.py
This PR wraps the SalesforceCDPConnection to prevent it from revoking the core token. Details explained [in the comments](https://github.com/monte-carlo-data/apollo-agent/pull/202/files#diff-990f39cb62f6d7533fc25036b135d11eaaeef6d0a05dc7e628e548286e09d1abR20).
> Prevent Salesforce Data Cloud from revoking access tokens

- apollo/agent/agent.py
- tests/test_aws_ca_bundle.py
This PR makes a small update to the custom AWS CA bundle functionality. When fetching a custom AWS CA bundle from secrets manager, use the default SSL CA bundle for the request to secrets manager.
The `AWS_CA_BUNDLE` env var can be preserved between invocations through warm containers which causes the agent lambda to use the custom ca bundle on the next invocation when attempting to retrieve the custom ca bundle from secrets manager.
> Use default CA bundle when retrieving from secret manager

- Dockerfile
- requirements.in
- requirements.txt
Even though a ticket hasn't been created, this is showing in Aikido.
Always upgrading `pip` is an attempt to see less VULNs.
> Upgrade gunicorn
