apollo/interfaces/generic/main.py
requirements.in
requirements.txt

Adds `flask-compress` library to automatically compress Flask responses

Add flask-compress to automatically compress responses

---

apollo/agent/proxy_client_factory.py
apollo/integrations/db/postgres_proxy_client.py
apollo/integrations/redshift/redshift_proxy_client.py
tests/test_postgres_client.py

- New Postgres proxy client that uses psycopg2 library.

KIL-2723 Postgres proxy client

---

.circleci/config.yml

Publish lambda image to Dockerhub

---

apollo/agent/proxy_client_factory.py
apollo/integrations/powerbi/powerbi_proxy_client.py
requirements.in
requirements.txt
tests/test_power_bi_client.py

- Adds a new PowerBI proxy client that wraps the existing HTTP Proxy client in order to generate an access token by performing an Azure Active Directory token exchange.

KIL-2848 PowerBI proxy client

---

apollo/integrations/db/mysql_proxy_client.py

MySQL connections in Azure agents were having the same issue fixed for Redshift with PR https://github.com/monte-carlo-data/apollo-agent/pull/63 
This PR adds code to force keep-alive to be enabled for MySQL connections and to send keep alive packets every 30 seconds.

Enabled TCP Keep Alive for MySQL connections

---

apollo/integrations/tableau/tableau_proxy_client.py

Add users read scope in tableau integration

add users read scope in tableau

---

requirements.in
requirements.txt

Update looker SDK version. We'd need to pull looker folders based on ID, the old SDK returns error.

update looker sdk version

---

requirements-cloudrun.txt
requirements.in
requirements.txt

Get `cryptography` upgraded to address security vulnerability.

Upgrade dependencies to address cryptography security vulnerability

---

requirements-azure.txt
requirements-cloudrun.txt
requirements.in
requirements.txt

Update idna to at least 3.7

---

requirements-dev.txt
requirements.in
requirements.txt

- updates Jinja2 to 3.1.4
- merged to dev

chore: update Jinja2

---

requirements-cloudrun.txt
requirements.in
requirements.txt

- `azure-identity==1.14.0` is vulnerable to `CVE-2024-35255` 
- This PR updates the following packages to the latest available versions:
- `azure-identity==1.17.1`
-  `azure-mgmt-storage==21.2.1`
-  `azure-storage-blob==12.20.0`

VULN: updated Azure packages to latest versions

---

README.md

Update the agent feature [lifecycle](https://docs.getmontecarlo.com/docs/integration-feature-lifecycles).

Set agent lifecycle to GA

---

.circleci/config.yml

- Introduced a new build job: `build-ok` present in both regular branches and merge queue branches which indicates the build completed successfully and the branch can be merged

Fix merge queue configuration

---

requirements-azure.in
requirements-azure.txt

-Upgrade the `aiohttp` package to fix a vulnerability issue

Upgrade aiohttp

---

Dockerfile

Minor version update for python for vulnerability fixes

VULN-419 Python version update

---

requirements-azure.txt
requirements-cloudrun.txt
requirements.txt

Merged this to dev and upgraded the agents in our apollo test dev account. It's been a few days now and no reported errors.

VULN-457 upgrade certifi pkg

---

Dockerfile

Added the git dependency to fix the issue collecting looker views.
Tested locally generating the agent lambda image:
```
$ docker build -t lambda_agent --target lambda --platform=linux/amd64 . 
```
Run the image locally:
```
$ docker run --rm --name lambda_agent --entrypoint /bin/sh -it lambda_agent  
```
Test git clone with script:
```
$ cat <<EOF > ./test_git_clone.py
import git
import os
import tempfile
import base64
def clone_repository(repo_url, ssh_key_string):
try:
with tempfile.NamedTemporaryFile(delete=False) as ssh_key_file:
ssh_key = base64.b64decode(ssh_key_string)
print(f"Writing SSH key: {ssh_key}")
ssh_key_file.write(ssh_key)
ssh_key_path = ssh_key_file.name
os.environ['GIT_SSH_COMMAND'] = f"ssh -i {ssh_key_path} -o StrictHostKeyChecking=no"
clone_dir = "/tmp/repo" …
```

MES-950: Added git dependency

---

Dockerfile

Removed sqllite package from the docker image to fix the VULN issue reported by Aikido

VULN-464: Remove sqllite package

---

requirements-azure.in
requirements-azure.txt

https://linear.app/montecarlodata/issue/VULN-472/small-upgrade-for-aiohttp

Upgrade aiohttp to 3.10.11

---

requirements-dev.txt
requirements.in
requirements.txt

Updated jinja2 from v3.1.4 to v3.1.5

VULN-492: Updated jinja2 from v3.1.4 to v3.1.5

---

Dockerfile

VULN-543: Upgraded docker base image from 3.12.7-slim to 3.12.9-slim

---

Dockerfile

- Upgraded pip to latest version to fix VULN-510

VULN-510: Upgraded pip to latest version

---

requirements-dev.txt
requirements.in
requirements.txt

Bump Jinja2 to v3.1.6 (to fix VULN-537)

Bump jinja2 for VULN-537

---

requirements.in
requirements.txt

Upgrade teradatasql [VULN-562]

---

apollo/agent/serde.py
apollo/integrations/db/db2_proxy_client.py
tests/test_db2_client.py
tests/test_salesforce_data_cloud_client.py

Handle serialization of DBAPITypeObjects in cursor description.

Fix db2 description serialization.
